name: Build Windows

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Install 7z
      uses: milliewalky/setup-7-zip@v2

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: beta

    - name: Build Flutter Windows executable
      run: |
        flutter pub get
        flutter build windows --release

    - name: Download xray core
      uses: robinraju/release-downloader@v1.12
      with:
        repository: 'XTLS/Xray-core'
        latest: true
        fileName: 'Xray-windows-64.zip'
        out-file-path: 'temp/'

    - name: Extract xray core
      shell: bash
      run: |
        mkdir -p temp/xray
        7z x temp/Xray-windows-64.zip -otemp/xray
        mkdir -p build/windows/x64/runner/Release/bin
        cp -r temp/xray/* build/windows/x64/runner/Release/bin/

    - name: Package Windows build
      shell: bash
      run: |
        mkdir -p release
        cp -r build/windows/x64/runner/Release/* release/
        cd release
        7z a -tzip ../xrayflutter_windows_release.zip *
        cd ..
        ls -lh xrayflutter_windows_release.zip

    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ github.ref_name }}-${{ github.run_number }}
        path: xrayflutter_windows_release.zip

    - name: Release Package
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: xrayflutter_windows_release.zip
